name: GitHub Action Auto-Doc
author: Pierre Nicolas Durette
description: A GitHub Action for generating GitHub Action Markdown documentation

branding:
  color: yellow
  icon: file-text

inputs:
  action_yaml_file:
    description: The path to GitHub Action's `action.yml` file
    required: false
    default: ./action.yml
  include_inputs:
    description: Test
    required: false
    default: "true"
  include_outputs:
    description: Test
    required: false
    default: "true"
  heading_size:
    description: Test
    required: false
    default: "3"
  template_file:
    description: Test
    required: false
    default: ./README.md
  target_file:
    description: Test
    required: false
    default: ./README.md
  marker_start:
    description: Test
    required: false
    default: "<!--doc_begin-->"
  marker_end:
    description: Test
    required: false
    default: "<!--doc_end-->"
  git_push:
    description: If true it will commit and push the changes
    required: false
    default: "false"
  git_push_user_name:
    description: If empty the name of the GitHub Actions bot will be used (i.e. `github-actions[bot]`)
    required: false
    default: "github-actions[bot]"
  git_push_user_email:
    description: If empty the no-reply email of the GitHub Actions bot will be used (i.e. `github-actions[bot]@users.noreply.github.com`)
    required: false
    default: "github-actions[bot]@users.noreply.github.com"
  git_commit_message:
    description: Commit message
    required: false
    default: "GitHub Action auto-doc"

runs:
  using: "composite"
  steps:
    # Setup Python
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    # Install Python
    - shell: bash
      run: |
        pip install --upgrade pip 
        pip install .
    # Run
    - shell: bash
      env:
        ACTION_YAML_FILE: ${{ inputs.action_yaml_file }}
        INCLUDE_INPUTS: ${{ inputs.include_inputs }}
        INCLUDE_OUTPUTS: ${{ inputs.include_outputs }}
        HEADING_SIZE: ${{ inputs.heading_size }}
        TEMPLATE_FILE: ${{ inputs.template_file }}
        TARGET_FILE: ${{ inputs.target_file }}
        MARKER_START: ${{ inputs.marker_start }}
        MARKER_END: ${{ inputs.marker_end }}
      run: python -m actiondoc
    # Git Push
    # See: https://github.com/actions/checkout#push-a-commit-using-the-built-in-token
    - shell: bash
      if: ${{ fromJSON(inputs.git_push) }}
      env:
        GIT_PUSH_USER_NAME: ${{ inputs.git_push_user_name}}
        GIT_PUSH_USER_EMAIL: ${{ inputs.git_push_user_email }}
        TARGET_FILE: ${{ inputs.target_file }}
        GIT_COMMIT_MESSAGE: ${{ inputs.git_commit_message }}
      run: |
        echo git config user.name "${GIT_PUSH_USER_NAME}"
        echo git config user.email "${GIT_PUSH_USER_NAME}"
        echo git add "${TARGET_FILE}"
        echo git commit -m "${GIT_COMMIT_MESSAGE}" "${TARGET_FILE}"
        echo git push