name: Generate Action Doc

on:
  pull_request:
    branches: ["main"]

permissions:
  # Required to push the changes
  contents: write

jobs:
  doc:
    name: Doc
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Generate Doc
      uses: ./
      with:
        git_push: true