name: Generate Action Doc

on:
  pull_request:
    branches: ["main"]

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: Generate Doc
      uses: ./
      with:
        include_outputs: false
        heading_size: 4