name: Tests

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  python:
    name: Python
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Python Setup
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Python Install
      run: |
        pip install --upgrade pip 
        pip install ".[tests]"
    - name: Run Tests
      run: |
        pytest -vv